In [1]:
import pandas as pd
import seaborn as sns
import numpy as np

In [2]:
df=pd.read_csv('emails.csv')
df.head()

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [3]:
df.shape

(5728, 2)

In [4]:
df.drop_duplicates(inplace=True)

In [5]:
df.shape

(5695, 2)

In [6]:
df.head()

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [10]:
df.spam.value_counts()

0    4327
1    1368
Name: spam, dtype: int64

In [11]:
df.isnull().sum()

text    0
spam    0
dtype: int64

In [59]:
x=df.text.values
y=df.spam.values

In [61]:
from sklearn.model_selection import train_test_split

In [62]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.30,random_state=42)

In [63]:
xtrain.shape

(3986,)

In [66]:
from sklearn.feature_extraction.text import CountVectorizer

In [67]:
cv=CountVectorizer()

In [68]:
x_train=cv.fit_transform(xtrain)

In [69]:
x_train.toarray()

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [30]:
from sklearn.naive_bayes import MultinomialNB

In [31]:
m=MultinomialNB()

In [70]:
m.fit(x_train,ytrain)

MultinomialNB()

In [71]:
x_test=cv.transform(xtest)

In [72]:
m.score(x_test,ytest)

0.9906377998829725

In [73]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [77]:
emails=['Hei, i am looking for some good tuitorial','hey you win an iphone x giveaway for free do the survey']

In [78]:
emails_detect = cv.transform(emails)

In [79]:
m.predict(emails_detect)

array([0, 1], dtype=int64)